import csv
import numpy as np

def export_counterfactuals_custom_to_csv(counterfactuals, iris_df, filename='counterfactuals.csv'):
    """
    Exports counterfactual examples to a CSV file in a custom format.

    The CSV file will contain rows of counterfactuals, where each row includes:
    - The original feature values from the input dataset.
    - The counterfactual feature values generated by the algorithm.
    - The corresponding weights assigned to the counterfactual features.

    The headers of the CSV file are formatted to clearly distinguish between original 
    values, counterfactual values, and weights.

    :param counterfactuals: A list of tuples, where each tuple contains the original instance 
                          and its corresponding counterfactual example.
    :param iris_df: The original DataFrame from which the feature names are extracted.
    :param filename: The name of the CSV file to save the counterfactual examples. 
                     Defaults to 'counterfactuals.csv'.
    """
    original_headers = [f'{name}_original' for name in iris_df.columns[:-1]]
    contrafactual_headers = [f'{name}_counterfactual' for name in iris_df.columns[:-1]]
    weight_headers = [f'{name}_weight' for name in iris_df.columns[:-1]]
    
    headers = original_headers + contrafactual_headers + weight_headers

    with open(filename, mode='w', newline='') as file:
        writer = csv.writer(file)
        
        writer.writerow(headers)
        
        for i in range(len(counterfactuals)):
            row =  list(counterfactuals[i][0]) + list(np.round(counterfactuals[i][1], 4))
            writer.writerow(row)
    
    print(f'{filename} saved!')